package dsd.codebenders.tournament_app.entities.streaming;

public enum EventType {
    ATTACKER_JOINED, ATTACKER_MUTANT_CREATED, ATTACKER_MUTANT_ERROR, ATTACKER_MUTANT_KILLED_EQUIVALENT,
    ATTACKER_MUTANT_SURVIVED, DEFENDER_JOINED, DEFENDER_KILLED_MUTANT, DEFENDER_MUTANT_CLAIMED_EQUIVALENT,
    DEFENDER_MUTANT_EQUIVALENT, DEFENDER_TEST_CREATED, DEFENDER_TEST_ERROR, DEFENDER_TEST_READY, GAME_CREATED,
    GAME_FINISHED, GAME_GRACE_ONE, GAME_GRACE_TWO, GAME_STARTED, SCORE_UPDATE
}
