version: '3.9'

services:
  database:
    image: "mysql:8.0"
    container_name: tournament_app_database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: YES
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-user}
      MYSQL_DATABASE: tournamentdb
    volumes:
      - dbvolume:/var/lib/mysql
      - ./docker/mysql_dump/tournamentdb_dump_v4.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: mysql tournamentdb --user=${DB_USERNAME:-user} --password=${DB_PASSWORD:-user} --execute "SELECT 1;"
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: polimifercodebenders/tournament_app_backend_image:1.0.0
    container_name: tournament_app_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/tournamentdb
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-user}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    image: polimifercodebenders/tournament_app_frontend_image:1.0.0
    container_name: tournament_app_frontend
    ports:
      - "${TA_FRONTEND_PORT:-80}:80"
    depends_on:
      - backend

volumes:
  dbvolume:
