version: '3.9'

services:
  database:
    image: "mysql:8.0"
    container_name: tournament_app_database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: YES
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-user}
      MYSQL_DATABASE: ${DB_SCHEMA:-tournamentdb}
    volumes:
      - dbvolume:/var/lib/mysql
    networks:
      - net
    healthcheck:
      test: mysql ${DB_SCHEMA:-tournamentdb} --user=${DB_USERNAME:-user} --password=${DB_PASSWORD:-user} --execute "SELECT 1;"
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: polimifercodebenders/tournament_app_backend_image:3.0.0
    container_name: tournament_app_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${DB_SCHEMA:-tournamentdb}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-user}
      TOURNAMENT-APP_TOURNAMENT_CLASS-SELECTION-TIME-DURATION: ${CLASS_SELECTION_DURATION:-60}
      TOURNAMENT-APP_TOURNAMENT-MATCH_BREAK-TIME-DURATION: ${BREAK_TIME_DURATION:-3600}
      TOURNAMENT-APP_TOURNAMENT-MATCH_PHASE-ONE-DURATION: ${PHASE_ONE_DURATION:-3600}
      TOURNAMENT-APP_TOURNAMENT-MATCH_PHASE-TWO-DURATION: ${PHASE_TWO_DURATION:-1800}
      TOURNAMENT-APP_TOURNAMENT-MATCH_PHASE-THREE-DURATION: ${PHASE_THREE_DURATION:-1800}
      TOURNAMENT-APP_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      TOURNAMENT-APP_WEB-SERVER_ADDRESS: http://localhost:${TA_FRONTEND_PORT:-80}
      CODE-DEFENDERS_DEFAULT-SERVERS_TOKEN: ${CODEDEFENDERS_DEFAULT_TOKEN:-}
    ports:
      - "${TA_BACKEND_PORT:-8080}:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
      args:
        REACT_APP_BACKEND_ADDRESS: http://localhost:${TA_BACKEND_PORT:-8080}
        REACT_APP_FRONTEND_ADDRESS: "http://localhost:${TA_FRONTEND_PORT:-80}"
    image: polimifercodebenders/tournament_app_frontend_image:3.0.0
    container_name: tournament_app_frontend
    ports:
      - "${TA_FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
      
networks:
  net:
    driver: bridge
volumes:
  dbvolume:
