version: '3.9'

services:
  database:
    image: "mysql:8.0"
    container_name: tournament_app_database
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: YES
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-user}
      MYSQL_DATABASE: ${DB_SCHEMA:-tournamentdb}
    volumes:
      - dbvolume:/var/lib/mysql
    healthcheck:
      test: mysql ${DB_SCHEMA:-tournamentdb} --user=${DB_USERNAME:-user} --password=${DB_PASSWORD:-user} --execute "SELECT 1;"
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: polimifercodebenders/tournament_app_backend_image:2.0.0
    container_name: tournament_app_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${DB_SCHEMA:-tournamentdb}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-user}
      CODE-DEFENDERS_TOKEN: SDUzl14p2gmoAWFNcEPleWP9uZekwSDC
      CODE-DEFENDERS_ADDRESS: http://codedef1.duckdns.org:8080/
      CODE-DEFENDERS_TEST-CLASS-ID: 100
      TOURNAMENT-APP_WEB-SERVER_ADDRESS: http://localhost:${TA_FRONTEND_PORT:-80}
    ports:
      - "${TA_BACKEND_PORT:-8080}:8080"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
      args:
        REACT_APP_BACKEND_ADDRESS: http://localhost:${TA_BACKEND_PORT:-8080}
    image: polimifercodebenders/tournament_app_frontend_image:2.0.0
    container_name: tournament_app_frontend
    ports:
      - "${TA_FRONTEND_PORT:-80}:80"
    depends_on:
      - backend

volumes:
  dbvolume:
